-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 13:58:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tienda_modelo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tienda_modelo` ;

-- -----------------------------------------------------
-- Schema tienda_modelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_modelo` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Tienda_revision_vehiculo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Tienda_revision_vehiculo` ;

-- -----------------------------------------------------
-- Schema Tienda_revision_vehiculo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tienda_revision_vehiculo` ;
USE `tienda_modelo` ;

-- -----------------------------------------------------
-- Table `tienda_modelo`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_modelo`.`cliente` ;

CREATE TABLE IF NOT EXISTS `tienda_modelo`.`cliente` (
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_modelo`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_modelo`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `tienda_modelo`.`proveedor` (
  `nif` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_modelo`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_modelo`.`Producto` ;

CREATE TABLE IF NOT EXISTS `tienda_modelo`.`Producto` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'Producto sin nombre',
  `precio` FLOAT NOT NULL,
  `proveedor_nif` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`, `proveedor_nif`),
  INDEX `fk_Producto_proveedor1_idx` (`proveedor_nif` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_proveedor1`
    FOREIGN KEY (`proveedor_nif`)
    REFERENCES `tienda_modelo`.`proveedor` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_modelo`.`cliente_has_Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_modelo`.`cliente_has_Producto` ;

CREATE TABLE IF NOT EXISTS `tienda_modelo`.`cliente_has_Producto` (
  `cliente_dni` VARCHAR(9) NOT NULL,
  `Producto_codigo` INT UNSIGNED NOT NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_dni`, `Producto_codigo`),
  INDEX `fk_cliente_has_Producto_Producto1_idx` (`Producto_codigo` ASC) VISIBLE,
  INDEX `fk_cliente_has_Producto_cliente_idx` (`cliente_dni` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_Producto_cliente`
    FOREIGN KEY (`cliente_dni`)
    REFERENCES `tienda_modelo`.`cliente` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_Producto_Producto1`
    FOREIGN KEY (`Producto_codigo`)
    REFERENCES `tienda_modelo`.`Producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Tienda_revision_vehiculo` ;

-- -----------------------------------------------------
-- Table `Tienda_revision_vehiculo`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tienda_revision_vehiculo`.`cliente` ;

CREATE TABLE IF NOT EXISTS `Tienda_revision_vehiculo`.`cliente` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tienda_revision_vehiculo`.`coche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tienda_revision_vehiculo`.`coche` ;

CREATE TABLE IF NOT EXISTS `Tienda_revision_vehiculo`.`coche` (
  `matricula` VARCHAR(10) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `cliente_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`matricula`, `cliente_codigo`),
  INDEX `fk_coche_cliente1_idx` (`cliente_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_coche_cliente1`
    FOREIGN KEY (`cliente_codigo`)
    REFERENCES `Tienda_revision_vehiculo`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tienda_revision_vehiculo`.`revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tienda_revision_vehiculo`.`revision` ;

CREATE TABLE IF NOT EXISTS `Tienda_revision_vehiculo`.`revision` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aceite` TINYINT NULL,
  `frenos` TINYINT NULL,
  `filtro` TINYINT NULL,
  `otros` VARCHAR(20) NULL,
  `coche_matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`, `coche_matricula`),
  INDEX `fk_revision_coche_idx` (`coche_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_revision_coche`
    FOREIGN KEY (`coche_matricula`)
    REFERENCES `Tienda_revision_vehiculo`.`coche` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
