print("Dibujo primero:\n")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****\n")
print("Primer ejercicio:\n") # Minimizar a 1 print que utiliza
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print("Segundo ejericio:\n") #Agrandar tamaño al doble de la flecha original
print("         *")
print("        * *")
print("       *   *")
print("      *     *")
print("     *       *")
print("    *         *")
print("   *           *")
print("  *             *")
print(" *               *")
print("******       ******")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *       *")
print("     *********\n")
print("Tercer ejericio:\n") #Duplicar la flecha y dejarla al lado
print("    *         *")
print("   * *       * *")
print("  *   *     *   *")
print(" *     *   *     *")
print("***   *** ***   ***")
print("  *   *     *   *")
print("  *   *     *   *")
print("  *****     *****\n")